name: Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - master  # Trigger when code is pushed to the `master` branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Log in to Docker Hub using the secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker images defined in docker-compose.yml
      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build  # Build images
          docker-compose -f docker-compose.yml push   # Push images to Docker Hub
