name: Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - master  # Trigger when code is pushed to the `main` branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to `main`

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (use GitHub secrets for security)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker images defined in docker-compose.yml
      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build  # Build images
          docker-compose -f docker-compose.yml push   # Push images to Docker Hub

      # Optionally deploy using docker-compose (you can use a remote server)
      - name: Deploy Docker Compose to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server "docker-compose -f /path/to/your/docker-compose.yml up -d"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store private key securely

